# Generated by Django 2.2.28 on 2024-11-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='published_date',
        ),
    ]
