# Generated by Django 2.2.28 on 2024-12-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
